# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog_translate_image.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TranslateImage(object):
    def setupUi(self, TranslateImage):
        TranslateImage.setObjectName("TranslateImage")
        TranslateImage.resize(347, 303)
        self.centralwidget = QtWidgets.QWidget(TranslateImage)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 341, 41))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 70, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 130, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.inpX = QtWidgets.QTextEdit(self.centralwidget)
        self.inpX.setGeometry(QtCore.QRect(80, 70, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.inpX.setFont(font)
        self.inpX.setObjectName("inpX")
        self.inpY = QtWidgets.QTextEdit(self.centralwidget)
        self.inpY.setGeometry(QtCore.QRect(80, 130, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.inpY.setFont(font)
        self.inpY.setObjectName("inpY")
        self.btnOk = QtWidgets.QPushButton(self.centralwidget)
        self.btnOk.setGeometry(QtCore.QRect(200, 200, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.btnOk.setFont(font)
        self.btnOk.setObjectName("btnOk")
        TranslateImage.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(TranslateImage)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 347, 21))
        self.menubar.setObjectName("menubar")
        TranslateImage.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(TranslateImage)
        self.statusbar.setObjectName("statusbar")
        TranslateImage.setStatusBar(self.statusbar)

        self.retranslateUi(TranslateImage)
        QtCore.QMetaObject.connectSlotsByName(TranslateImage)

    def retranslateUi(self, TranslateImage):
        _translate = QtCore.QCoreApplication.translate
        TranslateImage.setWindowTitle(_translate("TranslateImage", "TranslateImage"))
        self.label.setText(_translate("TranslateImage", "Translate Image"))
        self.label_2.setText(_translate("TranslateImage", "X : "))
        self.label_3.setText(_translate("TranslateImage", "Y : "))
        self.btnOk.setText(_translate("TranslateImage", "OK"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TranslateImage = QtWidgets.QMainWindow()
    ui = Ui_TranslateImage()
    ui.setupUi(TranslateImage)
    TranslateImage.show()
    sys.exit(app.exec_())
