from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AricmaticWindow(object):
    def setupUi(self, AricmaticWindow):
        AricmaticWindow.setObjectName("AricmaticWindow")
        AricmaticWindow.resize(1254, 444)
        self.centralwidget = QtWidgets.QWidget(AricmaticWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.photoInput1 = QtWidgets.QGraphicsView(self.centralwidget)
        self.photoInput1.setGeometry(QtCore.QRect(20, 50, 391, 341))
        self.photoInput1.setObjectName("photoInput1")
        self.photoInput2 = QtWidgets.QGraphicsView(self.centralwidget)
        self.photoInput2.setGeometry(QtCore.QRect(430, 50, 391, 341))
        self.photoInput2.setObjectName("photoInput2")
        self.photoOutput = QtWidgets.QGraphicsView(self.centralwidget)
        self.photoOutput.setGeometry(QtCore.QRect(840, 50, 391, 341))
        self.photoOutput.setObjectName("photoOutput")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 20, 381, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(430, 20, 381, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(840, 20, 381, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        AricmaticWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(AricmaticWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1254, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuOpen = QtWidgets.QMenu(self.menuFile)
        self.menuOpen.setObjectName("menuOpen")
        self.menuClear_2 = QtWidgets.QMenu(self.menuFile)
        self.menuClear_2.setObjectName("menuClear_2")
        self.menuAritmatika = QtWidgets.QMenu(self.menubar)
        self.menuAritmatika.setObjectName("menuAritmatika")
        self.menu0perations = QtWidgets.QMenu(self.menubar)
        self.menu0perations.setObjectName("menu0perations")
        self.menuClear = QtWidgets.QMenu(self.menubar)
        self.menuClear.setTitle("")
        self.menuClear.setObjectName("menuClear")
        AricmaticWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(AricmaticWindow)
        self.statusbar.setObjectName("statusbar")
        AricmaticWindow.setStatusBar(self.statusbar)
        self.actionImage_1 = QtWidgets.QAction(AricmaticWindow)
        self.actionImage_1.setObjectName("actionImage_1")
        self.actionImage_2 = QtWidgets.QAction(AricmaticWindow)
        self.actionImage_2.setObjectName("actionImage_2")
        self.actionClear_Image_1 = QtWidgets.QAction(AricmaticWindow)
        self.actionClear_Image_1.setObjectName("actionClear_Image_1")
        self.actionClear_Image_2 = QtWidgets.QAction(AricmaticWindow)
        self.actionClear_Image_2.setObjectName("actionClear_Image_2")
        self.actionInput_1 = QtWidgets.QAction(AricmaticWindow)
        self.actionInput_1.setObjectName("actionInput_1")
        self.actionInput_2 = QtWidgets.QAction(AricmaticWindow)
        self.actionInput_2.setObjectName("actionInput_2")
        self.actionClear_All = QtWidgets.QAction(AricmaticWindow)
        self.actionClear_All.setObjectName("actionClear_All")
        self.actionClear_Image1 = QtWidgets.QAction(AricmaticWindow)
        self.actionClear_Image1.setObjectName("actionClear_Image1")
        self.actionClear_Image2 = QtWidgets.QAction(AricmaticWindow)
        self.actionClear_Image2.setObjectName("actionClear_Image2")
        self.actionAddition = QtWidgets.QAction(AricmaticWindow)
        self.actionAddition.setObjectName("actionAddition")
        self.actionSubtraction = QtWidgets.QAction(AricmaticWindow)
        self.actionSubtraction.setObjectName("actionSubtraction")
        self.actionMultiplication = QtWidgets.QAction(AricmaticWindow)
        self.actionMultiplication.setObjectName("actionMultiplication")
        self.actionDivision = QtWidgets.QAction(AricmaticWindow)
        self.actionDivision.setObjectName("actionDivision")
        self.actionOR = QtWidgets.QAction(AricmaticWindow)
        self.actionOR.setObjectName("actionOR")
        self.actionAND = QtWidgets.QAction(AricmaticWindow)
        self.actionAND.setObjectName("actionAND")
        self.actionXOR = QtWidgets.QAction(AricmaticWindow)
        self.actionXOR.setObjectName("actionXOR")
        self.actionSave_Output = QtWidgets.QAction(AricmaticWindow)
        self.actionSave_Output.setObjectName("actionSave_Output")
        self.menuOpen.addAction(self.actionInput_1)
        self.menuOpen.addAction(self.actionInput_2)
        self.menuFile.addAction(self.menuOpen.menuAction())
        self.menuFile.addAction(self.menuClear_2.menuAction())
        self.menuFile.addAction(self.actionSave_Output)
        self.menuAritmatika.addAction(self.actionAddition)
        self.menuAritmatika.addAction(self.actionSubtraction)
        self.menuAritmatika.addAction(self.actionMultiplication)
        self.menuAritmatika.addAction(self.actionDivision)
        self.menu0perations.addAction(self.actionOR)
        self.menu0perations.addAction(self.actionAND)
        self.menu0perations.addAction(self.actionXOR)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAritmatika.menuAction())
        self.menubar.addAction(self.menu0perations.menuAction())
        self.menubar.addAction(self.menuClear.menuAction())

        self.retranslateUi(AricmaticWindow)
        QtCore.QMetaObject.connectSlotsByName(AricmaticWindow)

    def retranslateUi(self, AricmaticWindow):
        _translate = QtCore.QCoreApplication.translate
        AricmaticWindow.setWindowTitle(_translate("AricmaticWindow", "AricmaticWindow"))
        self.label.setText(_translate("AricmaticWindow", "Input 1"))
        self.label_2.setText(_translate("AricmaticWindow", "Input 2"))
        self.label_3.setText(_translate("AricmaticWindow", "Output"))
        self.menuFile.setTitle(_translate("AricmaticWindow", "File"))
        self.menuOpen.setTitle(_translate("AricmaticWindow", "Open"))
        self.menuClear_2.setTitle(_translate("AricmaticWindow", "Clear"))
        self.menuAritmatika.setTitle(_translate("AricmaticWindow", "Aritmatika 0perations"))
        self.menu0perations.setTitle(_translate("AricmaticWindow", "Logical 0perations"))
        self.actionImage_1.setText(_translate("AricmaticWindow", "Image 1"))
        self.actionImage_2.setText(_translate("AricmaticWindow", "Image 2"))
        self.actionClear_Image_1.setText(_translate("AricmaticWindow", "Clear Image 1"))
        self.actionClear_Image_2.setText(_translate("AricmaticWindow", "Clear Image 2"))
        self.actionInput_1.setText(_translate("AricmaticWindow", "Input 1"))
        self.actionInput_2.setText(_translate("AricmaticWindow", "Input 2"))
        self.actionClear_All.setText(_translate("AricmaticWindow", "Clear All"))
        self.actionClear_Image1.setText(_translate("AricmaticWindow", "Clear Image 1"))
        self.actionClear_Image2.setText(_translate("AricmaticWindow", "Clear Image 2"))
        self.actionAddition.setText(_translate("AricmaticWindow", "Addition"))
        self.actionSubtraction.setText(_translate("AricmaticWindow", "Subtraction"))
        self.actionMultiplication.setText(_translate("AricmaticWindow", "Multiplication"))
        self.actionDivision.setText(_translate("AricmaticWindow", "Division"))
        self.actionOR.setText(_translate("AricmaticWindow", "OR"))
        self.actionAND.setText(_translate("AricmaticWindow", "AND"))
        self.actionXOR.setText(_translate("AricmaticWindow", "XOR"))
        self.actionSave_Output.setText(_translate("AricmaticWindow", "Save Output"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AricmaticWindow = QtWidgets.QMainWindow()
    ui = Ui_AricmaticWindow()
    ui.setupUi(AricmaticWindow)
    AricmaticWindow.show()
    sys.exit(app.exec_())
