# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog_rotate_image.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RotateImage(object):
    def setupUi(self, RotateImage):
        RotateImage.setObjectName("RotateImage")
        RotateImage.resize(817, 261)
        self.centralwidget = QtWidgets.QWidget(RotateImage)
        self.centralwidget.setObjectName("centralwidget")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 20, 341, 41))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider.setGeometry(QtCore.QRect(30, 100, 591, 22))
        self.horizontalSlider.setMinimum(-360)
        self.horizontalSlider.setMaximum(360)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.btnOk_2 = QtWidgets.QPushButton(self.centralwidget)
        self.btnOk_2.setGeometry(QtCore.QRect(30, 140, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.btnOk_2.setFont(font)
        self.btnOk_2.setObjectName("btnOk_2")
        self.inpY_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.inpY_2.setGeometry(QtCore.QRect(650, 90, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.inpY_2.setFont(font)
        self.inpY_2.setObjectName("inpY_2")
        RotateImage.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(RotateImage)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 817, 31))
        self.menubar.setObjectName("menubar")
        RotateImage.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(RotateImage)
        self.statusbar.setObjectName("statusbar")
        RotateImage.setStatusBar(self.statusbar)

        self.retranslateUi(RotateImage)
        QtCore.QMetaObject.connectSlotsByName(RotateImage)

    def retranslateUi(self, RotateImage):
        _translate = QtCore.QCoreApplication.translate
        RotateImage.setWindowTitle(_translate("RotateImage", "RotateImage"))
        self.label_4.setText(_translate("RotateImage", "Rotate Image"))
        self.btnOk_2.setText(_translate("RotateImage", "OK"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RotateImage = QtWidgets.QMainWindow()
    ui = Ui_RotateImage()
    ui.setupUi(RotateImage)
    RotateImage.show()
    sys.exit(app.exec_())
