# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog_brightness_contrast.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1073, 302)
        self.slideBrightness = QtWidgets.QSlider(Dialog)
        self.slideBrightness.setGeometry(QtCore.QRect(160, 70, 751, 22))
        self.slideBrightness.setProperty("value", 30)
        self.slideBrightness.setOrientation(QtCore.Qt.Horizontal)
        self.slideBrightness.setObjectName("slideBrightness")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 60, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(40, 120, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.slideContrast = QtWidgets.QSlider(Dialog)
        self.slideContrast.setGeometry(QtCore.QRect(160, 130, 751, 22))
        self.slideContrast.setProperty("value", 60)
        self.slideContrast.setOrientation(QtCore.Qt.Horizontal)
        self.slideContrast.setObjectName("slideContrast")
        self.inpBright = QtWidgets.QTextEdit(Dialog)
        self.inpBright.setGeometry(QtCore.QRect(930, 60, 71, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.inpBright.setFont(font)
        self.inpBright.setObjectName("inpBright")
        self.inpContrast = QtWidgets.QTextEdit(Dialog)
        self.inpContrast.setGeometry(QtCore.QRect(930, 120, 71, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.inpContrast.setFont(font)
        self.inpContrast.setObjectName("inpContrast")
        self.btnOk = QtWidgets.QPushButton(Dialog)
        self.btnOk.setGeometry(QtCore.QRect(530, 230, 112, 34))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnOk.setFont(font)
        self.btnOk.setObjectName("btnOk")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Brightness : "))
        self.label_2.setText(_translate("Dialog", "Contrast : "))
        self.btnOk.setText(_translate("Dialog", "OK"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
